# Generated by Django 3.2 on 2021-07-21 14:54

from django.db import migrations
from django.db import utils


def reset_terms_of_use_for_social(apps, schema_editor):
    try:
        User = apps.get_model('account', 'CustomUser')
        for user in User.objects.all():
            if user.social_auth.exists():
                user.accepted_terms_of_use = False
                user.save()
    except utils.OperationalError:
        # it was one-time data migration. No one need it anymore,
        # and it fails if run from scratch without try-except
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_accepted_terms_of_use'),
    ]

    operations = [
        migrations.RunPython(reset_terms_of_use_for_social),
    ]
